name: Build on push
on: push
jobs:
  build:
    name: latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt update && sudo apt full-upgrade -y

      - name: Install dependencies
        run: sudo apt-get -y install quilt qemu-user-static debootstrap libarchive-tools dialog psmisc acl apt-cacher-ng aptly binutils-arm-linux-gnueabihf ccache debian-archive-keyring debian-keyring device-tree-compiler f2fs-tools gcc-10-cross-base gcc-arm-linux-gnueabihf gnupg1 lib32ncurses6 lib32tinfo6 libasan5-armhf-cross libatomic1-armhf-cross libbison-dev libc6-armhf-cross libc6-dev-armhf-cross libf2fs-format4 libf2fs5 libfdt1 libfile-fcntllock-perl libfl-dev libgcc-9-dev-armhf-cross libgcc-s1-armhf-cross libgomp1-armhf-cross liblz4-tool libncurses5-dev libnfsidmap2 libpython2.7 libpython2.7-dev libstdc++6-armhf-cross libtirpc-common libtirpc3 libubsan1-armhf-cross libusb-1.0-0-dev linux-libc-dev-armhf-cross lzop nfs-common nfs-kernel-server ntpdate patchutils pixz pv rpcbind systemd-container u-boot-tools

      - name: Nuke current Docker installation
        run: |
            sudo systemctl stop docker
            sudo apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
            sudo rm -rf /var/lib/docker
      
      - name: Re-install Docker
        run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            docker --version
      - name: Enable experimental features in Docker
        run: |
            sudo rm -rf /etc/docker/daemon.json
            echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
            sudo systemctl restart docker
      - name: Run build
        run: ./compile.sh BOARD="rockpro64" BRANCH="current" RELEASE="buster" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" BUILD_DESKTOP="no" BUILD_MINIMAL="yes"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: /home/runner/work/build/build/output/images/Armbian_20.11.0-trunk_Rockpro64_buster_current_5.8.13_minimal.img
          name: Umbrel_Rockpro64_dev.img