name: Build on push
on: push
jobs:
  build:
    name: latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Apt-get update
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get -y install quilt qemu-user-static debootstrap bsdtar

      - name: Nuke current Docker installation
        run: |
            sudo systemctl stop docker
            sudo apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
            sudo rm -rf /var/lib/docker
      
      - name: Re-install Docker
        run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            docker --version
      - name: Enable experimental features in Docker
        run: |
            sudo rm -rf /etc/docker/daemon.json
            echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
            sudo systemctl restart docker
      - name: Dependencies
        run: sudo apt install tree
      - name: Run build
        run: ./compile.sh BOARD="rockpro64" BRANCH="current" RELEASE="buster" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" BUILD_DESKTOP="no" BUILD_MINIMAL="yes"
      - name: Debug output
        run: tree .