name: Build on push
on: push
jobs:
  build:
    name: latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt update && sudo apt full-upgrade -y

      - name: Install dependencies
        run: sudo apt-get -y install quilt qemu-user-static debootstrap libarchive-tools dialog psmisc acl

      - name: Nuke current Docker installation
        run: |
            sudo systemctl stop docker
            sudo apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
            sudo rm -rf /var/lib/docker
      
      - name: Re-install Docker
        run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            docker --version
      - name: Enable experimental features in Docker
        run: |
            sudo rm -rf /etc/docker/daemon.json
            echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
            sudo systemctl restart docker
      - name: Run build
        run: ./compile.sh BOARD="rockpro64" BRANCH="current" RELEASE="buster" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" BUILD_DESKTOP="no" BUILD_MINIMAL="yes"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: /home/runner/work/build/build/output/images/Armbian_20.11.0-trunk_Rockpro64_buster_current_5.8.13_minimal.img
          name: Umbrel_Rockpro64_dev.img